# Generated by Django 3.2.16 on 2022-11-29 06:33

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [

    ]
