# Generated by Django 3.2.16 on 2022-12-09 07:34

from django.conf import settings
from django.db import migrations, models
import dog_walks.core.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_create_eat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('BLAGOEVGRAD', 'Благоевград'), ('BURGAS', 'Бургас'), ('VARNA', 'Варна'), ('VELIKOTARNOVO', 'Велико Търново'), ('VIDIN', 'Видин'), ('VRATSA', 'Враца'), ('GABROVO', 'Габрово'), ('DOBRICH', 'Добрич'), ('KYRDJALI', 'Кърджали'), ('KYUSTENDIL', 'Кюстендил'), ('LOVECH', 'Ловеч'), ('MONTANA', 'Монтана'), ('PAZARDZHIK', 'Пазарджик'), ('PERNIK', 'Перник'), ('PLEVEN', 'Плевен'), ('PLOVDIV', 'Пловдив'), ('RAZGRAD', 'Разград'), ('RUSE', 'Русе'), ('SILISTRA', 'Силистра'), ('SLIVEN', 'Сливен'), ('SMOLYAN', 'Смолян'), ('SOFIADISTRICT', 'Софийска област'), ('SOFIA', 'София'), ('STARAZAGORA', 'Стара Загора'), ('TARGOVISHTE', 'Търговище'), ('HASKOVO', 'Хасково'), ('SHUMEN', 'Шумен'), ('YAMBOL', 'Ямбол')], max_length=13)),
                ('city', models.CharField(max_length=50, validators=[dog_walks.core.validators.only_cyrillic_letters_validator])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('WATERFALL', 'Водопад'), ('CAVE', 'Пещера'), ('DAM', 'Язовир'), ('LANDMARKS', 'Природнa забележителност'), ('MONASTERY', 'Манастир'), ('MONUMENT', 'Паметник'), ('MUSEUM', 'Музей'), ('ECO_TRAIL', 'Екопътека'), ('OTHER', 'Други')], max_length=9)),
                ('dogs_are_welcome', models.CharField(choices=[('YES', 'Кучетата са добре дошли'), ('MAYBE', 'Позволено с уловие'), ('NO', 'Забранено за кучета')], max_length=5)),
                ('image', models.ImageField(upload_to='', verbose_name='Снимка')),
                ('entrance_fee', models.BooleanField(default=False)),
                ('holidays', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('displacement', models.FloatField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('HASSLE_FREE', 'Безпроблемно'), ('VERY_EASY', 'Много лесно'), ('EASY', 'Лесно'), ('AVERAGE', 'Средно'), ('HARD', 'Трудно'), ('VERY_HARD', 'Много трудно'), ('EXTREME', 'Екстремно')], max_length=11)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(on_delete=models.SET('Несъществуващ'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('longitude', 'latitude')},
            },
        ),
    ]
