# Generated by Django 3.2.16 on 2022-12-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dog_walks.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0005_add_upload_to_walk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eat',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[dog_walks.core.validators.OptionalSchemeURLValidator]),
        ),
        migrations.AlterField(
            model_name='night',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='night',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[dog_walks.core.validators.OptionalSchemeURLValidator]),
        ),
        migrations.AlterField(
            model_name='walk',
            name='type',
            field=models.CharField(choices=[('WATERFALL', 'Водопад'), ('CAVE', 'Пещера'), ('DAM', 'Язовир'), ('LANDMARKS', 'Природнa забележителност'), ('MONASTERY', 'Манастир'), ('MONUMENT', 'Паметник'), ('MUSEUM', 'Музей'), ('ECO_TRAIL', 'Екопътека'), ('PARK', 'Парк'), ('OTHER', 'Други')], max_length=9),
        ),
        migrations.AlterField(
            model_name='walk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walk',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[dog_walks.core.validators.OptionalSchemeURLValidator]),
        ),
    ]
