# Generated by Django 3.2.16 on 2022-12-09 07:39

from django.db import migrations

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
