# Generated by Django 3.2.16 on 2022-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_create_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatcomment',
            name='is_checked_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nightcomment',
            name='is_checked_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walkcomment',
            name='is_checked_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
