# Generated by Django 3.2.16 on 2022-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_appuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='have_permission_to_comment',
            field=models.BooleanField(default=True),
        ),
    ]
