# Generated by Django 3.2.16 on 2022-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_have_permission_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='have_permission_to_comment',
        ),
        migrations.AddField(
            model_name='appuser',
            name='have_permission_to_comment',
            field=models.BooleanField(default=True),
        ),
    ]
