# Generated by Django 3.2.16 on 2022-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_create_walk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='image',
            field=models.ImageField(upload_to='walk-places'),
        ),
    ]
